export const CATALOG = [
  {
    title: "Modern Sunglasses",
    price: 15,
    oldPrice: 25,
    category: "accessories",
    description: "Playful, polarized lenses with a subtle mirror finish.",
    image: "assets/product-glasses.jpg",
    rating: { rate: 4.7, count: 320 },
    discount: 40,
  },
  {
    title: "Aurora Leather Backpack",
    price: 189,
    oldPrice: 229,
    category: "bags",
    description: "Supple Italian leather with modular pockets and breathable back panel.",
    image: "assets/product-bag.jpg",
    rating: { rate: 4.8, count: 314 },
    discount: 18,
  },
  {
    title: "Helio Noise-Canceling Headphones",
    price: 289,
    oldPrice: 329,
    category: "audio",
    description: "Carbon fiber headband, adaptive ANC, and spatial audio tuned for clarity.",
    image: "assets/product-headphones.jpg",
    rating: { rate: 4.7, count: 742 },
    discount: 12,
  },
  {
    title: "Lumen Smart Lamp",
    price: 119,
    oldPrice: 149,
    category: "home",
    description: "Gradient LED array with sunrise automation and Matter compatibility.",
    image: "assets/product-lamp.jpg",
    rating: { rate: 4.5, count: 268 },
    discount: 15,
  },
  {
    title: "Pulse Fitness Tracker",
    price: 129,
    oldPrice: 179,
    category: "wearables",
    description: "Titanium shell, HRV insights, and 7-day battery on a single charge.",
    image: "assets/product-tracker.jpg",
    rating: { rate: 4.3, count: 509 },
    discount: 22,
  },
  {
    title: "Nimbus Mesh Sneakers",
    price: 159,
    oldPrice: 199,
    category: "footwear",
    description: "Featherweight knit upper with algae-based cushioning and reflective piping.",
    image: "assets/product-sneaker.jpg",
    rating: { rate: 4.6, count: 410 },
    discount: 19,
  },
  {
    title: "Polar Ceramic Mug Set",
    price: 48,
    oldPrice: 62,
    category: "kitchen",
    description: "Double-walled ceramic with a matte glaze and ergonomic thumb rest.",
    image: "assets/product-mug.jpg",
    rating: { rate: 4.4, count: 187 },
    discount: 10,
  },
  {
    title: "Chrono Luxe Watch",
    price: 329,
    oldPrice: 410,
    category: "watches",
    description: "Automatic movement with sapphire crystal and quick-release straps.",
    image: "assets/product-watch.jpg",
    rating: { rate: 4.9, count: 512 },
    discount: 20,
  },
  {
    title: "Street Oxford Shoes",
    price: 210,
    oldPrice: 260,
    category: "footwear",
    description: "Hybrid dress sneakers with flexible soles and hand-burnished leather.",
    image: "assets/product-shoe.jpg",
    rating: { rate: 4.5, count: 287 },
    discount: 19,
  },
  {
    title: "Weekend Linen Set",
    price: 98,
    oldPrice: 129,
    category: "clothing",
    description: "Relaxed-fit linen shirt with tapered drawstring trousers.",
    image: "assets/product-outfit.jpg",
    rating: { rate: 4.4, count: 230 },
    discount: 24,
  },
  {
    title: "Voyager Travel Tote",
    price: 145,
    oldPrice: 189,
    category: "bags",
    description: "Structured canvas tote with leather trim and magnetic laptop sleeve.",
    image: "assets/product-bag-2.jpg",
    rating: { rate: 4.6, count: 198 },
    discount: 23,
  },
  {
    title: "Varsity Wool Jacket",
    price: 240,
    oldPrice: 310,
    category: "outerwear",
    description: "Raglan cut wool blend with quilted lining and contrast cuffs.",
    image: "assets/product-jacket.jpg",
    rating: { rate: 4.7, count: 332 },
    discount: 22,
  },
];

export const HERO_IMAGE = "assets/hero.jpg";
